name: Type check, lint, and integration tests

on: push

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v3
      - name: Set up Python
        run: uv python install 3.12
      - name: Install dependencies
        run: uv sync
      - name: Run mypy on src
        run: uv run mypy --strict src
      - name: Run mypy on tests
        run: uv run mypy --strict tests
      - name: Run ruff check
        run: uv run ruff check
      - name: Run pytest
        run: uv run python -m pytest tests